apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-recorder
  namespace: nvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recorder
  template:
    metadata:
      labels:
        app: recorder
    spec:
      # Permite que o pod use o IP do host para achar as câmeras na LAN
      hostNetwork: true 
      containers:
      - name: ffmpeg-recorder
        image: camera-recorder:v1  # Você precisará fazer o load desta imagem no KIND
        volumeMounts:
        - name: video-storage
          mountPath: /1tb/video
      volumes:
      - name: video-storage
        hostPath:
          path: /1tb/video # Caminho físico no seu servidor Ubuntu
          type: DirectoryOrCreate
